### ISSUE TITLE
File referenced in README missing

### ISSUE THREAD

**Issue by akshithg** [ZHYfeng/Dependency#2]
Hi @ZHYfeng,
Congrats on the "Demystifying the Dependency Challenge in Kernel Fuzzing" work.

I'm trying to replicate the part where you build the kernel with bitcode using the instructions in the README and seems like one of the file referenced isn't preset. Specifically this one: https://github.com/ZHYfeng/Build_Linux_Kernel_Into_LLVM_Bitcode/tree/master/01-change_makefile

Will you please add the missing file?

Thank you!

**Comment by ZHYfeng** [comment]
Hi, @akshithg ,

Please refer to https://github.com/ZHYfeng/Generate_Linux_Kernel_Bitcode
I have made some updates and this can even work on kernel of linux v6.1.

And the old solution is in https://github.com/ZHYfeng/Generate_Linux_Kernel_Bitcode/tree/master/Achieve/01-change-makefile

**Comment by akshithg** [comment]
Thank you!
